title: Matt Chapman # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Sustainable Development Engineering with a concentration in Environmental Management with 3+ years of experience in analytics on sustainability. Currently at ITESM, and previously at Schneider Electric and Biofase.
  <br><br>
  Got a GPA:92/100
  <br><br>
  <a href="https://www.linkedin.com/in/luisrdzjim/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-S5RG0SPVW4 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
